#!/usr/bin/env python
import os
import shutil
import subprocess
import sys

TAG=sys.argv[1]

subprocess.check_call(['tox'])
subprocess.check_call(['git', 'tag', TAG])
try:
    subprocess.check_call(['tox'])
except subprocess.CalledProcessError:
    subprocess.check_call(['git', 'tag', '-d', TAG])
    sys.exit('Failed, untagging')

if os.path.exists('dist'):
    shutil.rmtree('dist')
os.mkdir('dist')

EXT = ('.zip', '.whl')
for dname in ['build/.tox/dist/', 'build/.tox/py27-wheel/tmp/dist/']:
    for fname in os.listdir(dname):
        if not fname.endswith(EXT):
            continue
        shutil.copy(os.path.join(dname, fname), 'dist')
