#!/usr/bin/env python
import os
import subprocess
import sys

PROD = False
if sys.argv[1:2] == ['--prod']:
    PROD = True

dist = os.path.abspath('dist')
files = (os.path.join(dist, fname) for fname in os.listdir(dist) if fname.endswith(('.zip', '.whl')))

toUpload = []
for fname in files:
    sig = fname+'.asc'
    if not os.path.exists(sig):
        sys.exit('Unsigned file, aborting: ' + fname)
    subprocess.check_call(['gpg', '--verify', sig])
    toUpload.extend([fname, sig])

if PROD:
    repository = 'pypi'
else:
    repository = 'testpypi'

subprocess.check_call(['twine', 'upload', '--repository', repository] + toUpload)
