#!/bin/sh
# Copyright (c) Moshe Zadka
# See LICENSE for details.
set -e
. env/bin/activate
FUNC_TEMP=`pwd`/_func_temp
rm -rf $FUNC_TEMP
mkdir -p $FUNC_TEMP/config
mkdir -p $FUNC_TEMP/messages
DEFAULTS="--messages $FUNC_TEMP/messages --config $FUNC_TEMP/config"
python -m ncolony.ctl $DEFAULTS add sleeper --cmd=`pwd`/env/bin/python --arg=-c --arg "import time, sys;print 'START';sys.stdout.flush();time.sleep(2);print 'STOP'"
twistd --rundir $FUNC_TEMP --pidfile $FUNC_TEMP/twistd.pid --logfile $FUNC_TEMP/twistd.log ncolony $DEFAULTS --freq 1
echo "sleeping for 5 seconds"
sleep 5
echo "waking up, asking for global restart"
python -m ncolony.ctl $DEFAULTS restart-all
echo "sleeping for 5 seconds"
sleep 5
echo "waking up, killing twistd"
kill `cat $FUNC_TEMP/twistd.pid`
while [ -f $FUNC_TEMP/twistd.pid ];do
	echo "Waiting for twistd to shut down"
	sleep 1
done
STARTS=`cat _func_temp/twistd.log |grep START |wc -l`
if [ "x$STARTS" != "x6" ]; then
	echo "START message appears wrong number of times: $STARTS" >&2
	exit 3
fi
STOPS=`cat _func_temp/twistd.log |grep STOP |wc -l`
if [ "x$STOPS" != "x4" ]; then
	echo "STOP message appears wrong number of times: $STOPS" >&2
	exit 3
fi
